export default [
  // 'runtime.info',
  'runtime.permission.requestAuthCode',
  // 'runtime.permission.requestOperateAuthCode', // 反馈式操作临时授权码
  // 'biz.alipay.pay',
  // 'biz.contact.choose',
  // 'biz.contact.complexChoose',
  // 'biz.contact.complexPicker',
  // 'biz.contact.createGroup',
  // 'biz.customContact.choose',
  // 'biz.customContact.multipleChoose',
  // 'biz.ding.post',
  'biz.map.locate',
  'biz.map.view',
  // 'biz.util.openLink',
  // 'biz.util.open',
  // 'biz.util.share',
  // 'biz.util.ut',
  // 'biz.util.uploadImage',
  // 'biz.util.uploadImageFromCamera',
  'biz.util.previewImage',
  // 'biz.util.datepicker',
  // 'biz.util.timepicker',
  // 'biz.util.datetimepicker',
  // 'biz.util.chosen',
  // 'biz.util.encrypt',
  // 'biz.util.decrypt',
  // 'biz.chat.pickConversation',
  // 'biz.telephone.call',
  // 'biz.navigation.setLeft',
  'biz.navigation.setTitle',
  // 'biz.navigation.setIcon',
  // 'biz.navigation.close',
  'biz.navigation.setRight',
  // 'biz.navigation.setMenu',
  // 'biz.user.get',
  // 'ui.progressBar.setColors',
  // 'device.base.getInterface',
  // 'device.connection.getNetworkType',
  // 'device.launcher.checkInstalledApps',
  // 'device.launcher.launchApp',
  // 'device.notification.confirm',
  // 'device.notification.alert',
  // 'device.notification.prompt',
  'device.notification.showPreloader',
  'device.notification.hidePreloader',
  // 'device.notification.toast',
  // 'device.notification.actionSheet',
  // 'device.notification.modal',
  'device.geolocation.get',
  'runtime.info',
  'biz.contact.choose',
  // 'device.notification.confirm',
  // 'device.notification.alert',
  // 'device.notification.prompt',
  'ui.webViewBounce.disable',
  'biz.ding.post',
  'biz.util.openLink',
  'biz.util.open',
  'biz.util.openSlidePanel',
  'biz.navigation.quit',
  'biz.cspace.saveFile',
  'biz.cspace.preview',
  'biz.cspace.chooseSpaceDir',
  'biz.util.downloadFile'
]
