export const RECORD_USERINFO = 'RECORD_USERINFO';
export const RETSET_USERINFO = 'RETSET_USERINFO';
export const GET_USERINFO = 'GET_USERINFO';
export const RECORD_DDCONFIG = 'RECORD_DDCONFIG';
export const GET_DDCONFIG = 'GET_DDCONFIG';
export const SHOW_LOADING = 'SHOW_LOADING';